#!/usr/bin/env bash
# Write a Bash script that transfers a file from our client to a server.

# Check if all the four parameters are provided
if [ "$#" -ne 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign the parameter to the variable
FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY_PATH=$4

# Disable strict host key checking
SCP_OPTIONS="-o StrictHostKeyChecking=no"

# Transfer the using scp
scp "$SCP_OPTIONS" -i "$SSH_KEY_PATH" "$FILE_PATH" "$USERNAME"@"$SERVER_IP":~/
