#!/usr/bin/env bash
# Web servers are the piece of software generating and serving

# Update the package list
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Start Nginx (it will automatically be listening on port 80)
sudo service nginx start

# Create a default HTML page with the string "Hello World"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Create a new configuration file for the redirection
sudo tee /etc/nginx/sites-available/redirect_me <<EOL
server {
    listen 80;
    server_name _;

    location /redirect_me {
        rewrite ^redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent; # Replace with the actual URL
    }

    # Additional server configurations can be added here if needed

    # Include the default Nginx configuration
    include /etc/nginx/sites-available/default;
}
EOL

# Create a symbolic link to enable the new configuration
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Test Nginx configuration
sudo nginx -t

# Reload Nginx to apply the changes
sudo service nginx reload
