#!/usr/bin/env bash
# Web servers are the piece of software generating and serving

# Update the package list
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create a default HTML page with the string "Hello World"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Replacemenr string
replacement_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/vickkykruz permanent;"

# Function to do so
sudo sed -i "s/server_name _;/$replacement_string/" /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
sudo service nginx restart
