#!/usr/bin/env bash
# This is a shell script that displays listening ports:
#	That only shows listening sockets
#	That shows the PID and name of the program to which each socket
#	 belongs.
netstat -p -l
