#!/usr/bin/env bash
# The script file troubleshoot the port, if it is not listening to port 80

# Check if the nginx is installed
if ! dpkg -l | grep -q nginx; then
    sudo apt-get update
    sudo apt-get install -y nginx
fi

# Check if Nginx is running
if ! systemctl is-active --quiet nginx; then
    sudo systemctl start nginx
fi

# Activate netstat, check if it is installed
if ! dpkg -l | grep net-tools; then
    sudo apt-get update
    sudo apt-get install -y net-tools
    sudo apt-get install -y iproute2
fi

# Check if any process is already listening on port 80
if ss -tulpn | grep -q :80; then
    echo "Nginx is already listening on port 80. Exiting..."
    exit 1
fi

# Check if Nginx is listening on port 80
if ! ss -tulpn | grep -q :80; then
    sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

    # Restart Nginx to apply changes
    sudo systemctl restart nginx

    # Check again if Nginx is now listening on port 80
    if ! ss -tulpn | grep -q :80; then
        echo "Failed to make Nginx listen on port 80. Please check the configuration manually."
        exit 1
    fi
fi
