#!/usr/bin/env bash
# This is a shell script that displays numbers from 1 to 100.
# Requirement:
#	Displays FizzBuzz when the number is a multiple of 3 and 5
#	Displays Fizz when the number is multiple of 3
#	Displays Buzz when the number is a multiple of 5
#	Otherwise, displays the number
#	In a list format

for ((i=1; i<=100; i++));
do
	((modfive = i % 5))
	((modthree = i % 3))

	if [ $modfive -eq 0 ] && [ $modthree -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $modthree -eq 0 ]
	then
		echo "Fizz"
	elif [ $modfive -eq 0 ]
	then
		echo "Buzz"
	else
		echo $i
	fi;
done
