#!/usr/bin/env bash
# This is a shell script that  displays the content of the file /etc/passwd,
# using the while loop + IFS.

while IFS= read -r line;
do
	user=$(echo "$line" | cut -d ":" -f 1)
	pass=$(echo "$line" | cut -d ":" -f 2)
	userid=$(echo "$line" | cut -d ":" -f 3)
	group=$(echo "$line" | cut -d ":" -f 4)
	info=$(echo "$line" | cut -d ":" -f 5)
	home=$(echo "$line" | cut -d ":" -f 6)
	shell=$(echo "$line" | cut -d ":" -f 7)

	echo -n "This user $user is part of the $group gang, "
	echo -n "lives in $home and rides $shell. "
	echo -n "$userid's place is protected by the passcode $pass, "
	echo "more info about the user here: $info"
done < "/etc/passwd"
