#!/usr/bin/env bash
# This is the shell that loop Best School 10 times using while loop
# But the 9th iteration should display Hi on a new line

i=0

while [ $i -lt 10 ];
do
	echo "Best School"
	if [ $i -eq 8 ]
	then
		echo "Hi"
	fi
	((i++))
done
