#!/usr/bin/env bash
# This is a shell scriot that displays the time for 12 hours and 59 minutes:

i=0

while [ $i -le 12 ];
do
	echo "Hour:" $i
	min=1
	while [ $min -lt 60 ];
	do
		echo $min
		((min++))
	done
	((i++))
done
