#!/usr/bin/env bash
# This is a shell script that display:
#	The content of the current directory
#	In a list format
#	Where only the part of the name after the first dash is displayed 
#	(refer to the example)

LIST=$(ls)

for dir in $LIST;
do
	echo "$dir" | cut -d "_" -f 2-
done
