#!/usr/bin/env bash
# This is a bash scriot that change the IP address to another file
cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2 localhost/' ~/hosts.new
sed -i '2i8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
