# Use an official Apache runtime as a parent image
FROM httpd:2.4

# Set the working directory to /usr/local/apache2/htdocs/
WORKDIR /usr/local/apache2/htdocs/

# Copy the content of the current directory to /usr/local/apache2/htdocs/ in the container
COPY . .

# Expose port 80 to the outside world
EXPOSE 80

