#!/bin/bash

# Install necessary packages (if not already installed)
apk update
apk add nginx

# Create the nginx user if it doesn't exist
if ! id -u nginx &>/dev/null; then
    adduser -D -H -u 101 -s /sbin/nologin nginx
fi

# Set the correct permissions for Nginx
chown -R nginx:nginx /var/lib/nginx
chown -R nginx:nginx /var/log/nginx

# Configure Nginx to run as the nginx user
sed -i 's/user\ \ nginx;/user\ \ nginx\ \;/g' /etc/nginx/nginx.conf

# Update the Nginx server block to listen on all active IPs on port 8080
sed -i 's/listen\ \ 80\;/listen\ \ 8080\ default\_server\;/g' /etc/nginx/conf.d/default.conf

# Start Nginx
nginx

# Keep the script running to keep the container alive
tail -f /dev/null
